### ISSUE TITLE
not working missing files 

### ISSUE THREAD

**Issue by rrnk235** [Kubia-Beta/Hold_to_Craft#10]
every time i try to start it it says its missing file try reinstalling ive reinstalled 4 times still save codes

**Comment by Kubia-Beta** [comment]
What file is missing?

Reinstall what?

**Comment by Kubia-Beta** [comment]
This issue appears to be the same as #9, I'm merging this issue and marking both as closed with the latest release:

[@Kubia-Beta/Hold_to_Craft@v2.3.0](https://github.com/Kubia-Beta/Hold_to_Craft/releases/tag/v2.3.0)

**Comment by rrnk235** [comment]
i was wating for you to veiw it sometimes people done ever look at these things i will post them here (the code execution could not proceed because VCRUNTIME40D.dll was not found) (MSVCP40D.dll WAS NOT FOUND) (could not proceed bc ucrtbased.dll was not found) i had tried to run as admin still did not work never went into first time setup

**Comment by rrnk235** [comment]
it was the samne issue ty
